### ISSUE TITLE
Try apply `id` to `id`

### ISSUE THREAD

**Issue by xieyuheng** [owo-lang/minitt-rs#26]
This reveals another problem with the type check algorithm in the paper.

My implementation can not check
```
let id_on_id: (A: type_t, A) -> A =
  id((A: type_t, A) -> A)(id)
```

Due to `checkI` can not infer type of type_t (the universe).

This can be solved by `universe in universe`, but the logic will be unsound.

**Comment by xieyuheng** [comment]
(I hope it is ok to discuss the paper in your issues,
since your repo is the most popular implementation of minitt.)

**Comment by ice1000** [comment]
It's solved by my `type in type` support, but can also be done with the lift operation in voile-rs.
